import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import NextTheme from "@/provider/NextTheme";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`bg-background text-foreground min-h-full flex flex-col ${poppins.className}`}>
        <NextTheme>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
          <Toaster />
        </NextTheme>
      </body>
    </html>
  );
}
